export default [
  {
    title: "Countries in the world",
    answers: [
      "Afghanistan",
      "Albania",
      "Algeria",
      "American Samoa",
      "Andorra",
      "Angola",
      "Anguilla",
      "Antarctica",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Aruba",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bhutan",
      "Bolivia",
      "Bonaire, Sint Eustatius and Saba",
      "Bosnia and Herzegovina",
      "Botswana",
      "Bouvet Island",
      "Brazil",
      "British Indian Ocean Territory",
      "Brunei Darussalam",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Cayman Islands",
      "Central African Republic",
      "Chad",
      "Chile",
      "China",
      "Christmas Island",
      "Cocos Islands",
      "Colombia",
      "Comoros",
      "Congo",
      "Congo",
      "Cook Islands",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Curaçao",
      "Cyprus",
      "Czechia",
      "Côte d'Ivoire",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Eswatini",
      "Ethiopia",
      "Falkland Islands [Malvinas]",
      "Faroe Islands",
      "Fiji",
      "Finland",
      "France",
      "French Guiana",
      "French Polynesia",
      "French Southern Territories",
      "Gabon",
      "Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Gibraltar",
      "Greece",
      "Greenland",
      "Grenada",
      "Guadeloupe",
      "Guam",
      "Guatemala",
      "Guernsey",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Heard Island and McDonald Islands",
      "Holy See",
      "Honduras",
      "Hong Kong",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Isle of Man",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jersey",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Korea",
      "Korea",
      "Kuwait",
      "Kyrgyzstan",
      "Lao People's Democratic Republic",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macao",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Martinique",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Mexico",
      "Micronesia",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Montserrat",
      "Morocco",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Caledonia",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Niue",
      "Norfolk Island",
      "Northern Mariana Islands",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Palestine",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Pitcairn",
      "Poland",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Republic of North Macedonia",
      "Romania",
      "Russian Federation",
      "Rwanda",
      "Réunion",
      "Saint Barthélemy",
      "Saint Helena, Ascension and Tristan da Cunha",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Martin",
      "Saint Pierre and Miquelon",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "San Marino",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Sint Maarten",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Georgia and the South Sandwich Islands",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "Sudan",
      "Suriname",
      "Svalbard and Jan Mayen",
      "Sweden",
      "Switzerland",
      "Syrian Arab Republic",
      "Taiwan",
      "Tajikistan",
      "Tanzania, United Republic of",
      "Thailand",
      "Timor-Leste",
      "Togo",
      "Tokelau",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Turks and Caicos Islands",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom of Great Britain and Northern Ireland",
      "United States Minor Outlying Islands",
      "United States of America",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Venezuela",
      "Viet Nam",
      "British Virgin Islands",
      "US Virgin Islands",
      "Wallis and Futuna",
      "Western Sahara",
      "Yemen",
      "Zambia",
      "Zimbabwe",
      "Åland Islands",
    ],
  },
  {
    title: 'Terms related to the word "sleep"',
    answers: [
      "Bed",
      "Pillow",
      "Blanket",
      "Dream",
      "Nightmare",
      "Sofa",
      "Dark",
      "Night",
      "Moon",
    ],
  },
  {
    title: "Fruits and Vegetables",
    answers: [
      "Apricots",
      "Artichokes",
      "Arugula",
      "Asparagus",
      "Avocados",
      "Basil",
      "Beets",
      "Black-eyed Peas",
      "Blood Oranges",
      "Broccoli",
      "Carrots",
      "Cauliflower",
      "Chard",
      "Cherries",
      "Corn",
      "Cucumber",
      "Eggplant",
      "Fava Beans",
      "Fennel",
      "Fiddleheads",
      "Garlic",
      "Figs",
      "Grapefruits",
      "Green Onions",
      "Kohlrabi",
      "Kumquats",
      "Medjool Dates",
      "Morels",
      "Mushrooms",
      "Navel Oranges",
      "Nectarines",
      "Nettles",
      "Lettuce",
      "Okra",
      "Parsley",
      "Passion Fruit",
      "Pea Beans",
      "Peaches",
      "Plums",
      "Potatoes",
      "Radish",
      "Raspberries",
      "Rhubarb",
      "Spinach",
      "Spring Onions",
      "Strawberries",
      "Tomatoes",
      "Turnips",
      "Apples",
      "Blackberries",
      "Blueberries",
      "Boysenberries",
      "Cabbage",
      "Carrots",
      "Collards",
      "Eggplants",
      "Grapes",
      "Grapefruits",
      "Kale",
      "Lemons",
      "Melons",
      "Mustard",
      "Okra",
      "Peppers",
      "Persimmons",
      "Plums",
      "Sapote",
      "Spinach",
      "Summer Squash",
      "Tomatillos",
      "Valencia Oranges",
      "Apples",
      "Asian Pears",
      "Beets",
      "Brussels Sprouts",
      "Carambola",
      "Cauliflower",
      "Celery",
      "Cherimoyas",
      "Chili Pepper",
      "Cranberries",
      "Edamame",
      "Grapes",
      "Green Beans",
      "Green Onions",
      "Guava",
      "Kiwi",
      "Leeks",
      "Lemongrass",
      "Limes",
      "Onions",
      "Oranges",
      "Parsnips",
      "Peaches",
      "Pears",
      "Peppers",
      "Persimmons",
      "Pineapples",
      "Pomegranates",
      "Pumpkins",
      "Quinces",
      "Radishes",
      "Rapini",
      "Raspberries",
      "Rutabaga",
      "Salsify",
      "Sapote",
      "Scallions",
      "Shallots",
      "Strawberries",
      "Sweet Potatoes",
      "Tomatillos",
      "Tomatoes",
      "Yams",
      "Brussels Sprouts",
      "Cabbage",
      "Corn",
      "Green Peas",
      "Guava",
      "Kale",
      "Tangelos",
      "Tangerines",
      "Winter Squash",
      "Artichokes",
      "Chayote Squash",
      "Collard Greens",
      "Cucumbers",
      "Endive",
      "Green Beans",
      "Green Bell Peppers",
      "Jalapenos",
      "Mustard Greens",
      "Snap Peas",
      "Snow Peas",
      "Swiss Chard",
      "Watercress",
      "Zucchini",
      "Acerola",
      "Blood Oranges",
      "Dragon Fruit",
      "Lingonberries",
      "Radicchio",
      "Red Apples",
      "Red Beets",
      "Red Cabbage",
      "Red Currants",
      "Red Grapefruits",
      "Red Grapes",
      "Red Onions",
      "Red Pears",
      "Red Peppers",
      "Red Potatoes",
      "Rose Hip",
      "Watermelon",
      "Acorn Squash",
      "Butternut Squash",
      "Clementine",
      "Hubbard Squash",
      "Mandarin Orange",
      "Mango",
      "Papayas",
      "Pumpkin",
      "Valencia Orange",
      "Bell Peppers",
      "Celery Hearts",
      "Chicory Greens",
      "Chili Peppers",
      "Cucumbers",
      "Garden Peas",
      "Lettuce",
      "Peas",
      "Romaine",
      "Sprouts",
      "Squash",
      "Alfalfa Sprouts",
      "Bok Choy",
      "Celeriac",
      "Celery",
      "Cilantro",
      "Iceberg Lettuce",
      "Jalapeno Peppers",
      "Jicama",
      "Pea Pods",
      "Rosemary",
      "Rutabagas",
      "Spaghetti Squash",
      "Thyme",
      "Wax Beans",
      "White Mushrooms",
      "Garbanzo Beans",
      "Lima Beans",
      "Pinto Beans",
      "Plantains",
      "Taro",
      "Water Chestnuts",
      "Amaranth",
      "Arugula",
      "Artichoke Hearts",
      "Asparagus",
      "Baby Corn",
      "Bamboo Shoots",
      "Chayote",
      "Chinese Spinach",
      "Crookneck Squash",
      "Cushaw Squash",
      "Daikon",
      "Endive Greens",
      "Escarole Greens",
      "Green Cabbage",
      "Hearts of Palm",
      "Leeks",
      "Onions",
      "Sugar Snap Peas",
      "Swiss Chard",
      "Yard-long Beans",
      "Acorn Squash",
      "Asparagus Tips",
      "Cantaloupe",
      "Cucumber",
      "Honeydew Melon",
      "Spinach",
      "String Beans",
      "White Potatoes",
      "Aubergine Eggplant",
      "Avocados",
      "Bananas",
      "Beet Greens",
      "Blackberries",
      "Collard Greens",
      "Grapefruit",
      "Guavas",
      "Kiwis",
      "Lychee",
      "Papaya",
      "Pears",
      "Sweet Corn",
      "White Button Mushrooms",
      "White Potatoes",
      "Tamarind",
      "Fried Plantains",
      "Mamey Sapote",
      "Jackfruit",
      "Soursop",
      "Lychee",
      "Passion Fruit",
      "Breadfruit",
      "Pomegranate",
      "Mango",
      "Cherimoya",
      "Persimmons",
      "Cherries",
      "Bananas",
      "Oranges",
      "Figs",
      "Watermelon",
      "Kiwi",
      "Grapes",
      "Guavas",
      "Pears",
      "Apples",
      "Peaches",
      "Papaya",
      "Nectarines",
      "Casaba Melon",
      "Peaches",
      "Asian Pear",
      "Red and White Currants",
      "Honeydew Melons",
      "Blackberries",
      "Strawberries",
      "Apricots",
      "Raspberries",
      "Cantaloupe",
      "Cranberries",
      "Carambola",
      "Avocado",
      "Olives",
      "Olives",
      "Avocados",
      "Carambola",
      "Cranberries",
      "Raspberries",
      "Blackberries",
      "Strawberries",
      "Casaba Melon",
      "Red and White Currants",
      "Asian Pear",
      "Almonds",
      "Cashew",
      "Coconuts",
      "Durian",
      "Indian Gooseberry",
      "Jaboticaba",
      "Jackfruit",
      "Lemons",
      "Lime",
      "Mangoes",
      "Mulberry",
      "Nectarine",
      "Olive",
      "Quince",
      "Peach",
      "Pomegranate",
      "Ajwain",
      "Amaranth",
      "Artichoke",
      "Bitter Melon",
      "Bitter Orange",
      "Broccoli Rabe",
      "Chard",
      "Chayotes",
      "Chervil",
      "Chicory",
      "Clove",
      "Coffee",
      "Dill",
      "Endives",
      "Ginger",
      "Grapefruit",
      "Horseradish",
      "Juniper",
      "Mint",
      "Olives",
      "Rhubarb Leaves",
      "Saffron",
      "Sesame Seeds",
      "Thistles",
      "Calamansi",
      "Gooseberries",
      "Japanese Apricots",
      "Pomelo",
      "Soursop",
      "Tamarind",
      "Tart Cherries",
      "Ackee",
      "Amla",
      "Avocado",
      "Banana",
      "Breadfruit",
      "Cashew Apple",
      "Cherimoya",
      "Chico",
      "Coconut",
      "Custard Apple",
      "Date Palm",
      "Fig",
      "Jackfruit",
      "Karuka",
      "Lemon",
      "Longan",
      "Loquat",
      "Mango",
      "Mangosteen",
      "Muskmelon",
      "Orange",
      "Passion Fruit",
      "Persimmon",
      "Pineapple",
      "Pomegranate",
      "Rambutan",
      "Rose Apple",
      "Salak",
      "Star Apple",
      "Star Fruit",
      "Tamarind",
      "Bell Peppers",
      "Chickpeas",
      "Chayote",
      "Courgette",
      "Aubergine",
      "Bok Choy",
      "Broccoli Romanesco",
      "Chinese Broccoli",
      "Chinese Cabbage",
      "Garden Cress",
      "Komatsuna",
      "Land Cress",
      "Mizuna",
      "Mustard",
      "Tatsoi",
      "Turnips",
      "Wasabi",
      "Watercress",
      "Black Cumin",
      "Black Salsify",
      "Breadroot",
      "Bush Carrot",
      "Cassava",
      "Chinese Artichokes",
      "Chinese Water Chestnut",
      "Chinese Yam",
      "Earthnut Pea",
      "Hog Potatoes",
      "Japanese Potatoes",
      "Jerusalem Artichokes",
      "Konjac",
      "New Zealand Yam",
      "Parsley Root",
      "Turmeric",
      "Yuca Root",
      "Cape Gooseberry",
      "Cayenne Pepper",
      "Garden Huckleberry",
      "Goji Berry",
      "Naranjilla",
      "Paprika",
      "Pepino",
      "Pimento",
      "Apriums",
      "Dates",
      "Green Almonds",
      "Lychees",
      "Mulberries",
      "Pluots",
      "Amanatsu",
      "Bergamot Orange",
      "Buddha’s Hand",
      "Blood Orange",
      "Calamondin",
      "Cara Cara",
      "Chinotto",
      "Citron",
      "Corsican Citron",
      "Desert Lime",
      "Etrog",
      "Eureka Lemon",
      "Finger Lime",
      "First Lady",
      "Florentine Citron",
      "Greek Citron",
      "Hyuganatsu",
      "Israel Citron",
      "Lemon",
      "Kabosu",
      "Kaffir Lime",
      "Key Lime",
      "Kinnow",
      "Kiyomi",
      "Kumquat",
      "Meyer Lemon",
      "Moroccan Citron",
      "Myrtle-leaved Orange",
      "Navel Orange",
      "Oroblanco Grapefruit",
      "Papeda",
      "Persian Lime",
      "Ponderosa Lemon",
      "Rangpur",
      "Round Lime",
      "Ruby Red Grapefruit",
      "Satsuma",
      "Shangjuan",
      "Shonan Gold",
      "Sudachi",
      "Sweet Lime",
      "Taiwan Tangerine",
      "Tangelo",
      "Tangerine",
      "Tangor",
      "Ugli Fruit",
      "Yuzu",
      "White Grapefruit",
      "Broad Beans",
      "Peas",
      "Turnips",
      "Red Bell Peppers",
      "Tomatoes ",
      "Apple",
      "Blackcurrant",
      "Breadfruit",
      "Coconut Meat",
      "Custard-Apple",
      "Date Fruit",
      "Elderberries",
      "Feijoa",
      "Gooseberries",
      "Java-Plum",
      "Jujube Fruit",
      "Kiwifruit",
      "Mandarin",
      "Pear",
      "Persimmon",
      "Pitaya",
      "Dragonfruit",
      "Pitanga",
      "Plantain",
      "Prunes",
      "Pummelo",
      "Quince",
      "Rose-Apple",
      "Sapodilla",
    ],
  },
  {
    title: "Things on a basic grocery list (excluding fruits and vegetables)",
    answers: [
      "Water",
      "Juice",
      "Bread",
      "Butter",
      "Cereal",
      "Coffee",
      "Cottage Cheese",
      "Eggs",
      "Flour",
      "Milk",
      "Oatmeal",
      "Pancakes",
      "Pasta",
      "Peanut Butter",
      "Pineapple",
      "Pizza",
      "Potatoes",
      "Rice",
      "Sausage",
      "Soy Milk",
      "Spaghetti",
      "Steak",
      "Tomatoes",
      "Yogurt",
      "Almonds",
      "Almond Milk",
      "Apple Cider",
      "Cheese",
      "Chicken",
      "Chocolate",
      "Snacks",
      "Sugar",
      "Tea",
      "Tofu",
      "Salt",
      "Pepper",
    ],
  },
  {
    title: "US States",
    answers: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
    ],
  },
  {
    title: "Languages spoken around the world",
    answers: [
      "Afrikaans",
      "Albanian",
      "Amharic",
      "Arabic",
      "Aragonese",
      "Armenian",
      "Asturian",
      "Azerbaijani",
      "Basque",
      "Belarusian",
      "Bengali",
      "Bosnian",
      "Breton",
      "Bulgarian",
      "Catalan",
      "Kurdish",
      "Chinese",
      "Corsican",
      "Croatian",
      "Czech",
      "Danish",
      "Dutch",
      "English",
      "Esperanto",
      "Estonian",
      "Faroese",
      "Filipino",
      "Finnish",
      "French",
      "Galician",
      "Georgian",
      "German",
      "Greek",
      "Guarani",
      "Gujarati",
      "Hausa",
      "Hawaiian",
      "Hebrew",
      "Hindi",
      "Hungarian",
      "Icelandic",
      "Indonesian",
      "Interlingua",
      "Irish",
      "Italian",
      "Japanese",
      "Kannada",
      "Kazakh",
      "Khmer",
      "Korean",
      "Kurdish",
      "Kyrgyz",
      "Lao",
      "Latin",
      "Latvian",
      "Lingala",
      "Lithuanian",
      "Macedonian",
      "Malay",
      "Malayalam",
      "Maltese",
      "Marathi",
      "Mongolian",
      "Nepali",
      "Norwegian",
      "Occitan",
      "Oriya",
      "Oromo",
      "Pashto",
      "Persian",
      "Polish",
      "Portuguese",
      "Punjabi",
      "Quechua",
      "Romanian",
      "Romansh",
      "Russian",
      "Scottish",
      "Serbian",
      "Serbo",
      "Shona",
      "Sindhi",
      "Sinhala",
      "Slovak",
      "Slovenian",
      "Somali",
      "Southern Sotho",
      "Spanish",
      "Sundanese",
      "Swahili",
      "Swedish",
      "Tajik",
      "Tamil",
      "Tatar",
      "Telugu",
      "Thai",
      "Tigrinya",
      "Tongan",
      "Turkish",
      "Turkmen",
      "Twi",
      "Ukrainian",
      "Urdu",
      "Uyghur",
      "Uzbek",
      "Vietnamese",
      "Walloon",
      "Welsh",
      "Western Frisian",
      "Xhosa",
      "Yiddish",
      "Yoruba",
      "Zulu",
    ],
  },
];
